### ISSUE TITLE
How do i translate this?

### ISSUE THREAD

**Issue by lvp11** [BTNGaming/btn_gcphone#12]
Hey,

How do i translate this? "taxi", "mecano" and services names?
https://forum.fivem.net/uploads/default/original/3X/6/8/68ebc3293259531030b5446066d67a859d50779e.png

Thanks!

**Comment by BTNGaming** [comment]
At the moment, that is not a bug, nor something that can be fixed because of the way it is coded into the phone. I will work on this in the future.
