### ISSUE TITLE
GPS

### ISSUE THREAD

**Issue by Ultrunz** [BTNGaming/btn_gcphone#13]
took a huge break but now i am back.
before the gps worked almost flawlessly i do have the newest gcphone addons and the newest version of your phone but i still have this issue.

It works using the 'favourites' in the phone, police, ambulance etc. But when i try to send my gps coords in sms it doesnt work.

there are no errors in the console either server or clientside.

Thanks in advance for any advice or help

**Comment by pilppe** [comment]
#11

**Comment by Ultrunz** [comment]
Legend thank you :) (L)

**Comment by Ultrunz** [comment]
Awesome dude that works! Appreciate it again
