### ISSUE TITLE
OneSync, everyone hears everyone.

### ISSUE THREAD

**Issue by LifeGoal** [BTNGaming/btn_gcphone#16]
Hi!

We have an issue on our server. When someone calls another person, they can hear everyone and everyone can hear them, even though they are not even close to each other.

**Comment by BTNGaming** [comment]
This is not fully optimized for One-Sync unfortunately. You can enable WebRTC and find a working RTC server to use it. That would fix your issues with it, also depends on if you're running Mumble or not.
