### ISSUE TITLE
messages to jobs

### ISSUE THREAD

**Issue by rapidengs** [BTNGaming/btn_gcphone#17]
Whenever i send a message to any service, like the police, ambulance, etc they receive that notification on their phone.
The only problem is that they get this message.
![bug1](https://user-images.githubusercontent.com/49963457/56697960-92a54680-66f0-11e9-8838-f55e5f4c58e1.jpg)

The problem is, that they cant use that GPS coordinates, because they are not selectable
![bug2](https://user-images.githubusercontent.com/49963457/56698012-bcf70400-66f0-11e9-897b-8ba6824d0396.jpg)

They only can reply to the telephone number that sent the message.

I cant seem to fix this.
Am i overlooking something?

Thanks in advance

**Comment by FRANkiller13** [comment]
I have the same problem..!

**Comment by FRANkiller13** [comment]
@rapidengs I make it....for me it works.. try and tell me if that works on you
[esx_addons_gcphone.zip](https://github.com/BTNGaming/btn_gcphone/files/3114557/esx_addons_gcphone.zip)

**Comment by rapidengs** [comment]
@FRANkiller13 i just tried it on my server and it works. Now i get 2 text messages. One with the message and one with the coordinates.
Thank you very much!
Much love!

**Comment by MeerkatRS** [comment]
I tried that addons_gcphone but it can't load the resource
