### ISSUE TITLE
Possible to make GCphone as an item from a store?

### ISSUE THREAD

**Issue by crixzgamez** [BTNGaming/btn_gcphone#19]
Hi, I was wondering if u knew how to add the phone as a required item in order to access it?
Ive looked everywhere and tried all the different things people say but I cant seem to get it to work.

**Comment by techniciantucker** [comment]
This is very simple just do a little work on searching the forums and you just need to turn the phone into an item and provide a inventory check and when the player presses the keybind.. :)

**Comment by techniciantucker** [comment]
> 
> 
> Hi, I was wondering if u knew how to add the phone as a required item in order to access it?
> Ive looked everywhere and tried all the different things people say but I cant seem to get it to work.

This is very simple just do a little work on searching the forums and you just need to turn the phone into an item and provide a inventory check and when the player presses the keybind.. :)

**Comment by crixzgamez** [comment]
it was pretty simple I was just new to the GTA scripts but understand it now :)
thanks
